spring:
  application:
    name: task-api
  profiles:
    active: hml

# Configuration pour l'environnement HML (Homologation)
server:
  port: 8080

logging:
  level:
    root: INFO
    com.larbotech: INFO

