name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      dockerfile_branch:
        description: 'Branch of docker-file-common repository to use'
        required: false
        default: 'main'
        type: string

jobs:
  build-and-deploy:
    name: Build and Deploy
    permissions:
      contents: read
      packages: write
    uses: tourem/github-actions-common/.github/workflows/maven-docker-build.yml@main
    with:
      # Configuration Maven
      java-version: '21'
      maven-version: '3.9'
      maven-pom: 'pom.xml'
      
      # Configuration Dockerfile
      dockerfile-repo: 'tourem/docker-file-common'
      dockerfile-branch: ${{ github.event.inputs.dockerfile_branch || 'main' }}
      
      # Modules Docker à builder
      docker-modules: |
        [
          {
            "name": "task-api",
            "artifact": "com.larbotech:task-api:jar",
            "config": "com.larbotech:task-api:zip:distribution"
          },
          {
            "name": "task-batch",
            "artifact": "com.larbotech:task-batch:jar",
            "config": "com.larbotech:task-batch:zip:distribution"
          }
        ]
      
      # Options
      skip-tests: false
      docker-build-enabled: true
    
    secrets: inherit

